datasetpath: "/home/roman/projects/ai/NYU_HAND_POSE_DATASET/dataset"
model_name: hglass_2_1
dataset: nyu
cubic_size: 280
subsetLength: -1

num_epoch: 40
batch_size: 32

RotAugment: 1
comjitter: 1
RandDotPercentage: 0.15 #PixDropOut
scale_aug: 1

use_fp16: 0

save_freq: 10

paralelization_type: DDP
device_IDs: 0,1,2,3
default_cuda_id: '0'
ngpus_per_node: "4"
rank: 0

LossFunction: L1
train_mode: normal

optimizer: adam
lr: 0.001
weight_decay: 2.0e-05


